MlynekV2/Controllers/JsController.cs
using MlynekV2.Models;
using MlynekV2.Services;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MlynekV2.Controllers
{
    public class JsController : Controller
    {
        // GET: Js
        public ActionResult Index()
        {
            return View();
        }

        public string inicjuj(int gracz1, int gracz2, string typBialych, string typCzarnych, string poziom, string kolejnoscWezlow, string algorytm)
        {
            Gra.createNewInstance();
            Gra.getInstance().dodajZmienne(typBialych, typCzarnych, poziom, kolejnoscWezlow, algorytm);
            return "true"; 
        }

        public Gracz getGracz(string kolor)
        {
            if(Convert.ToInt32(kolor) == 1)
            {
                return Gra.getInstance().gracz1;
            }else
            {
                return Gra.getInstance().gracz2;
            }
        }

        public string obsluzRuch(double xNowe, double yNowe, int kolorGracza, double xStare, double yStare,string nazwaPionka)
        {
            //0, 0- niepoprawny ruch
            //x,y - poprawny ruch- miejsce gdzie nalezy postawic pionek
            Punkt nowyPunkt = new Punkt(xNowe, yNowe);
            Punkt staryPunkt = new Punkt(xStare, yStare);
           WynikRuchu p = Gra.getInstance().obsluzRuch(nowyPunkt, getGracz(kolorGracza.ToString()), staryPunkt, nazwaPionka);
           return new JsonTransformService().SerializeToString(p);
        }

        public string usunPionek(double x, double y)
        {
            Gra.getInstance().usunZPlanszyInformacjeOStarymPunkcie(new Punkt(x, y));
            return  new JsonTransformService().SerializeToString(new Komunikat("c# usnuniete"));
        }

        public string znajdzRuchy(string kolor)
        {
            List<Ruch> listaRuchow=  Gra.getInstance().znajdzMozliwePrzesuniecia(Convert.ToInt32(kolor), Gra.getInstance().pole);
            return new JsonTransformService().SerializeToString(listaRuchow);
        }

        public string kompZnajdzRuch(string kolor, bool jestMlynek)
        {
            ObiektZwracanyPrzezAlfaBeta ruchKomp = Gra.getInstance().kompZnajdzNajlepszeMiejsceIPionek(getGracz(kolor), jestMlynek);
            return new JsonTransformService().SerializeToString(ruchKomp);
        }
    }
}

MlynekV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<script>
    localStorage.setItem("api-inicjuj-url", "@Url.Action("inicjuj", "Js")");
    localStorage.setItem("api-obsluzRuch-url", "@Url.Action("obsluzRuch", "Js")");
    localStorage.setItem("api-usunPionek-url", "@Url.Action("usunPionek", "Js")");
    localStorage.setItem("api-znajdzRuchy-url", "@Url.Action("znajdzRuchy", "Js")");
    localStorage.setItem( "api-znajdzNajlRuch-url", "@Url.Action("kompZnajdzRuch", "Js")");

</script>

<html>
<head>
    @RenderSection("styles", required: false)
    @RenderSection("scripts", required: false)

</head>
<body style="background-color:#FFFF99">

    <div style="margin-left:60px">
        @RenderBody()
    </div>

</body>
</html>